## Counting Unique Values

In [1]:
# %pdb on or %debug = Acitvate the debugger in Jupyter
import numpy as np

In [4]:
x = np.arange( 20 )
x.ndim

1

In [8]:
x = np.arange(11 *5).reshape(11, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54]])

In [19]:
x[5, :2]

array([25, 26])

In [21]:
x.mean(axis=1)

array([ 2.,  7., 12., 17., 22., 27., 32., 37., 42., 47., 52.])